[#56] Fix `implicit capture of 'this' via '[=]' is deprecated`
UE and C++ really need to make up their minds... This reverts:
[#31] Update for UE5 - Fix "'this' Cannot Be Explicitly Captured"
(34f83a38986e6008c034ae06665d7bf957a04e21), which was made when updating
to UE 5.

Fixes:
> Error C4855 : implicit capture of 'this' via '[=]' is deprecated
> in '/std:c++20'